#pragma once

// default but used in macros
#define TAPPING_TERM 150
#define PERMISSIVE_HOLD

#define ENABLE_RGB_MATRIX_BREATHING
#define RGB_MATRIX_TIMEOUT 300000
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BREATHING