#pragma once

// default but used in macros
#define TAPPING_TERM 150
#define PERMISSIVE_HOLD

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_REACTIVE_NEXUS